version: "3.0"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD="yourStrong(!)Password"
    ports: 
      - 127.0.0.1:1433:1433
    networks:
      - sql_network
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - sql_network
    depends_on:
      - mssql

networks:
  sql_network:
    driver: bridge
